In [3]:
def extractdse(from_date, to_date, instrument):

    # Importing packages
    import pandas as pd, datetime, lxml
    from selenium import webdriver
    from selenium.webdriver.support.select import Select
    from bs4 import BeautifulSoup
    from IPython.display import display_html

    # load the driver, download chrome driver and put the .exe file in C:/Windows
    driver = webdriver.Firefox()

    # load DSE data archive site
    driver.get("https://www.dsebd.org/day_end_archive.php")

    # deal with the pop up warning
    from selenium.common.exceptions import NoAlertPresentException
    from selenium.webdriver.common.keys import Keys
    from selenium.webdriver.common.action_chains import ActionChains
    import time

    try:
        alert = driver.switch_to.alert
        alert.accept()
    except NoAlertPresentException:
        print("No alert here")

    # beginning day
    start_date = driver.find_element_by_id("DayEndSumDate1").send_keys(from_date)

    # end day
    end_date = driver.find_element_by_id("DayEndSumDate2").send_keys(to_date)

    # instrument
    inst = Select(driver.find_element_by_name("Symbol"))
    inst.select_by_visible_text(instrument)

    # generate the table
    driver.find_element_by_name("ViewDayEndArchive").click()

    # extract the table
    soup = BeautifulSoup(driver.page_source, "html.parser")
    tables = soup.find_all("table")
    the_table = pd.read_html(driver.page_source, header=0)[len(tables) - 5]
    the_table = the_table.drop(["#"], axis=1)

    # write the file to xlsx
    file_name = instrument + "-" + from_date + "-" + "to" + "-" + to_date + ".xlsx"
    the_table.to_excel(file_name, index=False)

    return the_table

In [4]:
extractdse("2019-06-30", "2019-07-15", "ACFL")

No alert here

,DATE,TRADING CODE,LTP*,HIGH,LOW,OPENP*,CLOSEP*,YCP,TRADE,VALUE (mn),VOLUME
0,2019-07-15,ACFL,33.4,34.5,32.7,34.0,33.0,34.4,472,10.444,312367
1,2019-07-14,ACFL,34.0,35.7,34.0,35.7,34.4,34.8,274,5.653,163286
2,2019-07-11,ACFL,35.5,36.1,34.3,35.8,34.8,35.8,403,10.002,283136
3,2019-07-10,ACFL,35.8,36.6,35.7,36.1,35.8,36.4,332,9.401,260897
4,2019-07-09,ACFL,36.4,38.0,36.0,37.9,36.4,37.9,580,15.660,421781
5,2019-07-08,ACFL,37.6,38.8,37.5,38.8,37.9,38.7,667,22.519,593147
6,2019-07-07,ACFL,38.8,39.3,37.7,39.0,38.7,38.8,940,37.395,973081
7,2019-07-04,ACFL,38.8,39.4,36.2,36.6,38.8,36.6,1662,68.340,1791687
8,2019-07-03,ACFL,36.9,37.7,36.3,37.4,36.6,37.4,496,12.523,340634
9,2019-07-02,ACFL,37.8,37.8,35.4,35.4,37.4,35.3,1268,52.348,1429578
10,2019-06-30,ACFL,35.5,35.6,34.4,34.6,35.3,34.5,463,8.484,241669